const clients = [
  {
    id: 1,
    first_name: "Derby",
    last_name: "Denson",
    email: "ddenson0@toplist.cz",
    orders: [
      { product: "Books", price: "$234.47" },
      { product: "Computers", price: "$36.24" },
    ],
  },
  {
    id: 2,
    first_name: "Clarance",
    last_name: "Persicke",
    email: "cpersicke1@tumblr.com",
    orders: [
      { product: "Tools", price: "$167.03" },
      { product: "Music", price: "$55.72" },
      { product: "Electronics", price: "$201.57" },
    ],
  },
  {
    id: 3,
    first_name: "Julita",
    last_name: "Littleton",
    email: "jlittleton2@livejournal.com",
    orders: [{ product: "Health", price: "$103.12" }],
  },
  {
    id: 4,
    first_name: "Guglielma",
    last_name: "Jelley",
    email: "gjelley3@google.co.jp",
    orders: [{ product: "Games", price: "$33.22" }],
  },
  {
    id: 5,
    first_name: "Margie",
    last_name: "Cunde",
    email: "mcunde4@homestead.com",
    orders: [{}],
  },
  {
    id: 6,
    first_name: "Vinny",
    last_name: "Jinks",
    email: "vjinks5@twitpic.com",
    orders: [{ product: "Sports", price: "$19.75" }],
  },
  {
    id: 7,
    first_name: "Justin",
    last_name: "Ring",
    email: "jring6@4shared.com",
    orders: [{}],
  },
  {
    id: 8,
    first_name: "Rodolfo",
    last_name: "Rudolfer",
    email: "rrudolfer7@nih.gov",
    orders: [{ product: "Games", price: "$132.45" }],
  },
  {
    id: 9,
    first_name: "Amelia",
    last_name: "Kemp",
    email: "akemp8@cdc.gov",
    orders: [{ product: "Garden", price: "$25.29" }],
  },
  {
    id: 10,
    first_name: "Vernon",
    last_name: "Schimoni",
    email: "vschimoni9@wordpress.org",
    orders: [{ product: "Garden", price: "$25.29" }],
  },
  {
    id: 11,
    first_name: "Mattias",
    last_name: "Bryant",
    email: "mbryanta@google.es",
    orders: [{ product: "Garden", price: "$25.29" }],
  },
  {
    id: 12,
    first_name: "Arlyne",
    last_name: "Olle",
    email: "aolleb@jiathis.com",
    orders: [{ product: "Books", price: "$161.52" }],
  },
  {
    id: 13,
    first_name: "Babbette",
    last_name: "McPhelimey",
    email: "bmcphelimeyc@baidu.com",
    orders: [{ product: "Books", price: "$161.52" }],
  },
  {
    id: 14,
    first_name: "Mallory",
    last_name: "Sket",
    email: "msketd@dot.gov",
    orders: [{ product: "Books", price: "$161.52" }],
  },
  {
    id: 15,
    first_name: "Case",
    last_name: "Langthorn",
    email: "clangthorne@addthis.com",
    orders: [{ product: "Books", price: "$1" }],
  },
  {
    id: 16,
    first_name: "Johnny",
    last_name: "Mion",
    email: "jmionf@dmoz.org",
    orders: [{}, {}],
  },
  {
    id: 17,
    first_name: "Berk",
    last_name: "Southon",
    email: "bsouthong@nydailynews.com",
    orders: [{}],
  },
  {
    id: 18,
    first_name: "Xavier",
    last_name: "Pycock",
    email: "xpycockh@uol.com.br",
    orders: [{}],
  },
  {
    id: 19,
    first_name: "Winnah",
    last_name: "Geane",
    email: "wgeanei@homestead.com",
    orders: [{}, {}, {}],
  },
  {
    id: 20,
    first_name: "Cordie",
    last_name: "Bransom",
    email: "cbransomj@goodreads.com",
    orders: [{}],
  },
];

module.exports = clients;
