const employees = [
  {
    id: 1,
    first_name: "Carine",
    last_name: "Prevett",
    adress: "1st Floor",
    salary: "1500",
  },
  {
    id: 2,
    first_name: "Garfield",
    last_name: "Moland",
    adress: "PO Box 89048",
    salary: "3900",
  },
  {
    id: 3,
    first_name: "Annaliese",
    last_name: "Bankhurst",
    adress: "15th Floor",
    salary: "1400",
  },
  {
    id: 4,
    first_name: "Martin",
    last_name: "Lamberth",
    adress: "16th Floor",
    salary: "1230",
  },
  {
    id: 5,
    first_name: "Rebecca",
    last_name: "Richardin",
    adress: "9th Floor",
    salary: "780",
  },
  {
    id: 6,
    first_name: "Heddi",
    last_name: "Leggett",
    adress: "Room 1888",
    salary: "1500",
  },
  {
    id: 7,
    first_name: "Fanchette",
    last_name: "Magowan",
    adress: "Suite 8",
    salary: "2020",
  },
  {
    id: 8,
    first_name: "Fay",
    last_name: "Hinners",
    adress: "Room 518",
    salary: "1042",
  },
  {
    id: 9,
    first_name: "Mercy",
    last_name: "Joseff",
    adress: "Apt 1073",
    salary: "5999",
  },
  {
    id: 10,
    first_name: "Anne-marie",
    last_name: "Alliot",
    adress: "Suite 27",
    salary: "362",
  },
  {
    id: 11,
    first_name: "Rois",
    last_name: "Breakspear",
    adress: "Apt 22",
    salary: "1000",
  },
  {
    id: 12,
    first_name: "Beltran",
    last_name: "Castella",
    adress: "Suite 13",
    salary: "5142",
  },
  {
    id: 13,
    first_name: "Smitty",
    last_name: "Mazey",
    adress: "Apt 48",
    salary: "12000",
  },
  {
    id: 14,
    first_name: "Candy",
    last_name: "Salmoni",
    adress: "1st Floor",
    salary: "223",
  },
  {
    id: 15,
    first_name: "Royal",
    last_name: "Calder",
    adress: "10th Floor",
    salary: "50",
  },
  {
    id: 16,
    first_name: "Gian",
    last_name: "Veldstra",
    adress: "Suite 61",
    salary: "0",
  },
  {
    id: 17,
    first_name: "Quintilla",
    last_name: "Ruberry",
    adress: "Suite 100",
    salary: "1999",
  },
  {
    id: 18,
    first_name: "Berkeley",
    last_name: "Boyton",
    adress: "Room 1373",
    salary: "2345",
  },
  {
    id: 19,
    first_name: "Milka",
    last_name: "Murr",
    adress: "Suite 1",
    salary: "1040",
  },
  {
    id: 20,
    first_name: "Elle",
    last_name: "Lamar",
    adress: "Room 1569",
    salary: "6999",
  },
];

module.exports = employees;
